### PR TITLE
Bump nginx to v1.10.0

### PR DESCRIPTION
**Pull request by shmick**
Bump nginx to v1.9.15

### CODE REVIEW

**Comment by shmick** [comment]
Updated to nginx 1.10.0

**Comment by MatthewVance** [comment]
Thank you. I appreciate you helping me to watch out for updates. I plan to merge once I have a chance. 

I'm also keeping my eye out to bump the script to use OpenSSL 1.1.0 which should land around May 12 per the [release strategy](https://www.openssl.org/policies/releasestrat.html) page. I'm looking forward to it because it will support ChaCha20+Poly1305 cipher suite which will probably replace AES256-GCM as the first cipher in my supported list.

**Comment by MatthewVance** [comment]
I should have caught this a minute ago. I only plan to merge the v1.9.15 change. Version v1.10.0 is actually for the stable branch. I plan to stick with the mainline version as it has proven quite stable and allows me to get the new features faster.

**Comment by shmick** [comment]
Ah, good catch. From what I can see, 1.11 will end up replacing 1.9

https://www.nginx.com/blog/nginx-1-10-1-11-released/

**Comment by MatthewVance** [comment]
Good find. I hadn't seen that post. 1.11 it will be then.

**Comment by MatthewVance** [comment]
Is there an easy way for merge the part for v1.9.15 only without doing a cherry pick?

**Comment by shmick** [comment]
I'll close this one and you can use [this](https://github.com/MatthewVance/nginx-build/pull/5) one

**Comment by MatthewVance** [comment]
👍

**Pull request closed without merging**
